name: iZenith
version: 1.10
main: net.bobmandude9889.iZenith.Main
author: bobmandude9889
depend: [CustomGUIAPI,Vault]

commands:
   ranks:
      usage: /<command>
      description: Shows a list of ranks
   donator:
      usage: /<command>
      description: Warps to the donator area
   pvp:
      usage: /<command>
      description: Warps to the pvp area
   wild:
      usage: /<command>
      description: Warps to the wild
   nether:
      usage: /<command>
      description: Warps to the Nether
   end:
      usage: /<command>
      description: Warps to the END
   reminder:
      usage: /<command>
      description: Reminder based commands.
   nomobs:
      usage: /<command>
      description: Enables selection tool.
   setnomobs:
      usage: /<command>
      description: Sets no mob area.
   nooutfire: 
      usage: /<command>
      description: NO OUT FIRE
   commandblk:
      usage: /<command>
      description: command
   voteshop:
      usage: /<command> [create,delete,get,set,add] [player]
      description: vote shop commands
   startbroadcast:
      usage: /<command>
      description: Starts the auto broadcast
   setyoutube:
      usage: /<command> <player>
      description: Adds the youtube prefix to a player
   paycheck:
      usage: /<command> [vote]
      description: Pay checker
      
permissions:
   izenith.nooutfire:
      description: Gives access to /nooutfire
      default: OP
   izenith.paycheck:
      description: Gives access to /paycheck
      default: OP
   izenith.setnomobs:
      description: Gives access to /setnomobs
      default: OP
   izenith.setyoutube:
      description: Gives access to /setyoutube
      default: OP
   izenith.startbroadcast:
      description: Gives access to /startbroadcast
      default: OP
   izenith.voteshop:
      description: Gives access to /voteshop
      default: OP